name: Build and test

on:
  push:
  pull_request:
    branches: [master]

jobs:
  build-and-test-osx:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: script/ci/build-and-test.sh
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          PACT_BROKER_FEATURES: publish_pacts_using_old_api

  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: script/ci/build-and-test.sh
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          PACT_BROKER_FEATURES: publish_pacts_using_old_api
